root:
  true
env:
  browser: true
  es2022: true
  "vue/setup-compiler-macros": true
extends:
  - "plugin:vue/vue3-essential"
  - "@nuxtjs/eslint-config-typescript"
  - "plugin:nuxt/recommended"
parser:
  "vue-eslint-parser"
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: "latest"
  sourceType: "module"
  vueFeatures:
    - "filter": true
    - "interpolationAsNonHTML": false
plugins:
  - "vue"
  - "@typescript-eslint"
rules:
  "comma-dangle": ["error", "always-multiline"]
  "no-multiple-empty-lines": off
  "space-before-function-paren": off
  "no-multi-spaces": off
  "no-console": off
  "vue/no-v-html": off
  "vue/html-self-closing": off
  "vue/singleline-html-element-content-newline": off
  "vue/no-parsing-error": off
  "key-spacing": off
  